### ISSUE TITLE
Modelagem BD

### ISSUE THREAD

**Issue by DrielyGuerreiro** [Matheus-Msantos/PI4#5]
Estrutura das tabelas e colunas da aplicação

**Data inicio - Data fim**
29/09 - 03/09

**Comment by Matheus-Msantos** [comment]
![Modelagem_BD](https://user-images.githubusercontent.com/66855345/131269070-9b3d2e09-87b4-483b-b97d-d10e06838950.jpg)

**Comment by Matheus-Msantos** [comment]
![Captura de tela 2021-09-01 204615](https://user-images.githubusercontent.com/66855345/131759661-efb916f3-3018-4e17-a233-7c32627c8a0c.jpg)

**Comment by Matheus-Msantos** [comment]
Adicionamos uma coluna de preço em eventos

**Comment by Matheus-Msantos** [comment]
Adicionar uma coluna de quantidades de produtos comprados na tabela de pedidos (eventos_user)
